### ISSUE TITLE
Ensure reticulate works in windows

### ISSUE THREAD

**Issue by WilliamsTravis** [earthlab/cft#118]
While our github actions setup installs and runs cft on windows, the correct conda environment does not appear to be consistently accessible by cft in other windows installations.

**Comment by WilliamsTravis** [comment]
On my windows 10 installation it appears as though there is some environment variable confusion when using reticulate in parallel. Setting the RETICULATE_PYTHON path variable (path to the cft environment) in a file called .Renviron in the R_USER folder seems to fix the issue, at least in RStudio. It seems like a bit much to ask users to do this, perhaps we could automate this step in install_py_deps or find a better solution.

**Comment by mbjoseph** [comment]
Let's try inserting `use_condaenv('cft', required = TRUE)` here: https://github.com/earthlab/cft/blob/master/R/subsetting.R#L195

If this works, we can remove all the user calls to `use_condaenv()`.
