### ISSUE TITLE
Unable to find conda binary

### ISSUE THREAD

**Issue by acrunyon** [earthlab/cft#123]
When running cftdata(), I receive the following error:
[1] "Saving local files to C:\\Users\\achildress\\Documents\\R\\win-library\\3.5\\acadia_national_park"
   |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
  one node produced an error: Unable to find conda binary. Is Anaconda installed?

To find the conda install for reticulate library, I used the following line:
Sys.setenv(PATH= paste("C:/Users/achildress/AppData/Local/Continuum/anaconda2/Library/bin",Sys.getenv()["PATH"],sep=";"))

After that line of code, it was able to extract packages.

**Comment by mbjoseph** [comment]
@WilliamsTravis any thoughts on this? We know that anaconda is installed, and reticulate can find it interactively, but not when using the `cftdata()` function...

**Comment by WilliamsTravis** [comment]
Yeah, I started to reply but realized...I don't actually have a clue. I did notice that she is using anaconda 2, so it must be a previously installed installation. I just need to login into windows and experiment with different installations. You know one thought is that Anaconda usually asks where to install (defaulting to the home folder). I wonder if a different location was chosen.
________________________________

**Comment by acrunyon** [comment]
I thought about this last weekend and was going to try switching to python/anaconda 3 to see if that changes anything.  Won't be able to get to it until later in the week, but can let you guys know if anything changes.

**Comment by WilliamsTravis** [comment]
Cool, thanks! This is good to figure out, hopefully it will be an easy fix.

**Comment by WilliamsTravis** [comment]
Well, I finally signed into my windows os, removed anaconda 3 and everything associated with it, reinstalled anaconda2 in the AppData/Local/Continuum folder (was defaulting to my home directory on my machine), reinstalled cft, and successfully ran a test. 

@acrunyon Did you set your system-level conda path variable at any point (during or after installation)? I always set mine during installation cause it's easier than doing it later, though it flashes red at you and many people probably wouldn't do it.  I have a pretty strong feeling that this is it. If it is, we couldn't really set the path for people, but should probably add in a blip about it in the getting started guide.

**Comment by acrunyon** [comment]
@WilliamsTravis @mbjoseph I was finally able to get the package to run. My colleague was able to get everything running, according to the guidance. I started by uninstalling Anacond2 and all versions of python2.7 - incl. in ArcGIS and switched to miniconda3 and Python 3.7. Still didn't work so I updated to R 3.6.1 (version Annie used) and now it works. I'm not sure which combination of this actually resolved the problem.  Thanks for your help.

**Comment by WilliamsTravis** [comment]
@acrunyon Oh right, ArcGIS! It still uses python 2 and probably changes the environment paths....well I hadn't thought of that. Okay, this is good to know, ArcGIS is common enough that I should add a mention of that sort of thing in the installation docs. Thanks!

**Comment by raerickson** [comment]
I'm having this problem in the Docker image, `earthlab/cft/`. I'm running Docker on Windows, but that should not matter. Any thoughts on what I should try?

**Comment by mbjoseph** [comment]
The Docker image is now fixed, and we've updated the documentation to recommend that people install miniconda with the reticulate package, which should ensure that it's discoverable by the reticulate package, e.g., 

https://github.com/earthlab/cft/commit/2ff8c2653647f3d52cab000f7912f3f9c18e39c3#diff-3254677a7917c6c01f55212f86c57fbfR16 

Thanks @acrunyon and @rerickson-usgs for raising & confirming this issue!
