### ISSUE TITLE
suggestion for docker image for tutorials

### ISSUE THREAD

**Issue by raerickson** [earthlab/cft#124]
I'm working my way through the Introduction tutorial. Would you please consider adding the `ggrepel` package to your Docker image. That way users will not need to install the package every time they start Docker. 

Also, if you prefer, I would be happy to fork the project and do a pull request. Please tag me here so I know you want me to do this.

**Comment by raerickson** [comment]
Also, I'm unable to go through the [Intro](https://www.earthdatascience.org/cft/articles/cft-intro.html) with the docker image because I get this error 

>   |                                                  | 0 % ~calculating  Error in checkForRemoteErrors(val) : 
  2 nodes produced errors; first error: Python shared library not found, Python bindings not loaded.
Use reticulate::install_miniconda() if you'd like to install a Miniconda Python environment.

I tried running `reticulate::install_miniconda()`, but get an install error.

**Comment by raerickson** [comment]
I've forked the project and am trying to debug right now. I'll either close this issue when I do a pull request or update the issue with what I find

**Comment by mbjoseph** [comment]
Thanks @rerickson-usgs - ggrepel is now added in the Dockerfile (a cinch), but this reticulate business seems trickier. I'll dig into this. Seems like there may have been some upstream changes in reticulate that are causing this issue...

**Comment by mbjoseph** [comment]
As a temporary fix, you can install miniconda (in a discoverable location) and the python dependencies for cft by running the following lines inside the Docker container: 

```r
reticulate::install_miniconda()
cft::install_py_deps()
```

**Comment by raerickson** [comment]
@mbjoseph Thank you for your help. I did not do a pull request because I was waiting for the Travis tests to complete. 

I'm having slow internet today at home, hence my troubleshooting is limited. However, I think I can get the examples to work using Native on in Windows and your Docker Image via the command line. (i.e., `run ... /bin/bash` then launching R). I cannot get the examples to work in the RStudio image running in Docker. I still get the Anaconda cannot be found error.
