### ISSUE TITLE
proj4string(x): CRS object has comment, which is lost in output

### ISSUE THREAD

**Issue by acrunyon** [earthlab/cft#127]
Hi @mbjoseph & @WilliamsTravis  -- When I run the function cftdata() I get the following warning messages:
Warning messages:
1: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum unknown in CRS definition
2: In proj4string(x) : CRS object has comment, which is lost in output
3: In proj4string(x) : CRS object has comment, which is lost in output
4: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
5: In proj4string(x) : CRS object has comment, which is lost in output
6: In proj4string(x) : CRS object has comment, which is lost in output
7: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
8: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
9: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
10: In showSRID(uprojargs, format = "PROJ", multiline = "NO") :
  Discarded datum Unknown based on WGS84 ellipsoid in CRS definition
> 
What is going on here?

**Comment by WilliamsTravis** [comment]
Hi, were you using a shapefile or a park name? Could you print out the function call?

**Comment by acrunyon** [comment]
I was using the exact script from the vignette because I know that it works, or at least did a couple of weeks ago. My colleague is having the same issue as well. 

## download some data
d <- cftdata(park = "Acadia National Park", parameters = "pr",
             years = c(2020, 2021), models = "CCSM4", scenarios = "rcp85",local_dir = getwd())

**Comment by WilliamsTravis** [comment]
Hmm, I couldn't recreate it on my linux machine. I'll try it on Windows tonight. Is your colleague also using windows?

Also, is this affecting the outputs?

**Comment by acrunyon** [comment]
Thanks! Yes - all we use is Windows.  Outputs still look OK.

**Comment by WilliamsTravis** [comment]
From a quick glance it looks like its related to [this](http://rgdal.r-forge.r-project.org/articles/PROJ6_GDAL3.html).

The proj package changed how they want their crs information given recently. Now they want "authority:code" or wkt, so perhaps if I replace this [line](https://github.com/earthlab/cft/blob/3549bdfbbec06f12a457eaf9ff32ab15089897aa/R/reference.R#L15) (and any other like it) with "epsg:4326" it will fix this warning.

I can't get to it right away, but it looks like your outputs aren't being affected so hopefully this is just an annoyanec. Also, according to that first article, "the warnings are at present overly cautious".

Okay, thanks for catching it,  I'll ping you when I fix this.

**Comment by mbjoseph** [comment]
Thanks @acrunyon I'm able to reproduce this on Linux. We'll see if we can fix it! I suspect Travis is right that this may have something to do with rgdal's transition to PROJ6.

**Comment by mbjoseph** [comment]
Fixed this in #137
