### ISSUE TITLE
Unclear how to use package with point data

### ISSUE THREAD

**Issue by acrunyon** [earthlab/cft#134]
I would like to use this package, but instead of pulling all cells within a named park boundary, by specifying lat/lon and pulling the cell it is within. I recall you guys mentioning that the package allowed that, but I didn't find it anywhere in the documentation and get errors when playing around with it on my own. Is this something that can be done? If so, could you add it to the vignette?

**Comment by mbjoseph** [comment]
Hey @acrunyon  - IIRC the package only supports polygons.

I'll touch base with @WilliamsTravis to see whether we want to support points as well, but in the meantime, a simple workaround would be to buffer your point a little bit to convert from a point to a polygon.

**Comment by acrunyon** [comment]
So the package accepts polygons but not points?

If it helps with your decision, it's actually pretty important for our future use of this package that it has the ability to use lat/lon to extract climate data.  We often want to pull from an exact grid cell and will almost never extract from the whole park unit.

**Comment by mbjoseph** [comment]
That's right @acrunyon - all of the functionality that we've built so far is around polygons - thanks for the hint about needing exact grid cells! If the buffer size that is arbitrarily small, you should be able to ensure that you're only extracting from one grid cell. But, that's an extra step, which might add some complexity for the user who really wants to work with point data.

**Comment by irangwala** [comment]
Hi Max, Travis: I would second the need to be able to select the region by lat, lon  either as a point location or a rectangular bounding box. That will increase the utility of CFT quite a bit. Right now I am using a shapefile to extract data from CFT and then a different script to extract data for point location from that. Thanks for looking into it. Imtiaz

**Comment by mbjoseph** [comment]
The cft package now supports point extraction @acrunyon and @irangwala #139

@acrunyon on an unrelated note, I removed all of the python dependencies for this package, so it should be easier to install.

**Comment by irangwala** [comment]
Great. Thanks Max. Will check it out. Imtiaz

On Aug 27, 2020 9:08 AM, Max Joseph <notifications@github.com> wrote:

The cft package now supports point extraction @acrunyon<https://github.com/acrunyon> and @irangwala<https://github.com/irangwala> #139<https://github.com/earthlab/cft/pull/139>

@acrunyon<https://github.com/acrunyon> on an unrelated note, I removed all of the python dependencies for this package, so it should be easier to install.
