### ISSUE TITLE
Spatial Alignment Issue

### ISSUE THREAD

**Issue by DrWKID** [earthlab/cft#144]
The following code call produces this spatial alignment issue:
[cft_alignment_problem2.pdf](https://github.com/earthlab/cft/files/6680704/cft_alignment_problem2.pdf)
```
# Set variables
path <- "/Users/natasha/Downloads/temp/"
shapefile_name <- "SGI_exterior_boundary" #"test_shapefile" 

# Read in the area of interest
aoi <- readOGR(dsn=paste(path,shapefile_name,sep=""), 
               layer=shapefile_name)

d <- cftdata(aoi = aoi, area_name = "test", parameters = "pr",
             years = c(2050, 2050), models = "bcc-csm1-1", scenarios = "rcp45",
             local_dir = path, ncores=parallel::detectCores())

# align CRS
crs(aoi)
crs(raster(d$local_path))
aoi_reproject <- spTransform(aoi,crs(raster(d$local_path))) #sp::CRS("+init=EPSG:4326"))
crs(aoi_reproject)

# plot to confirm
pdf(paste(path,"cft_alignment_problem2.pdf",sep=""), height=8.5, width=11)
plot(raster(d$local_path), col=terrain.colors(100))
plot(aoi_reproject, add=TRUE)
dev.off()
```

**Comment by DrWKID** [comment]
So I've figured out that the issue is that the shapefile uses EPSG 5070 and the MACAv2metdata uses EPSG 4326. While sp::transform converts the shapefile to the CRS of the MACAv2metdata, it provides a latitude minimum ~0.519 degrees~49.8 km south of the available MACAv2metdata (~12.5 grid cells). What's happening is that the get_aoi_indices assumes that the smallest distance between the latitude min from MACAv2metdata and latitude min from the shapefile are in the same grid reference. They are not. This however squishes the grid index call in the API query. 

I haven't found a fix, but I'm fairly confident that this is the problem.

**Comment by DrWKID** [comment]
The problem seems to be that the shapefile is outside of the bounds of the climate data, which excludes the Florida Keys (for which the shapefile includes). I have updated the code to throw an error message if this happens and will submit a pull request. Once this is accepted, you will need to reinstall CFT.

<img width="873" alt="Screen Shot 2021-06-26 at 6 33 08 PM" src="https://user-images.githubusercontent.com/32376901/123529654-a1f8f380-d6af-11eb-88a8-cfe6ba0f5822.png">

**Comment by DrWKID** [comment]
Upon further testing with shapefiles within the bounds of mainlaind CONUS, the spatial alignment issue persisted:
<img width="725" alt="Screen Shot 2021-07-08 at 12 48 37 PM" src="https://user-images.githubusercontent.com/32376901/124975116-e444fd80-dfea-11eb-8069-a8fc9c4f5057.png">

This issue was fixed with code changes to get_aoi_indexes(), get_aoi_info() and the addition of a function get_aoi_latlon_vectors(). A new pull request absorbing the previous one and this one are being submitted.

Here is the same image with fixes applied:
<img width="725" alt="Screen Shot 2021-07-08 at 12 48 59 PM" src="https://user-images.githubusercontent.com/32376901/124975398-39810f00-dfeb-11eb-8538-6632617a2255.png">

Note that some of the polygons are too small and do not contain a full climate pixel. Addressing this should be submitted as a separate issue.

**Comment by DrWKID** [comment]
This problem does not seem to be resolved. It seems there may be an issue with the rasters crop function used in the new get_aoi_latlon_vectors() function. I'm exploring it further. Stay tuned...

**Comment by ttuff** [comment]
This issue has been resolved in the new cft release. The original cause of your error was a failure of the gdal package that cft relied on but is now deprecated. Please see the readme file for the new cft release to use our new working spatial functions.
