### ISSUE TITLE
cftdata() throwing error from makeCluster() command in the parallel package

### ISSUE THREAD

**Issue by Janelle88** [earthlab/cft#146]
I've run into an error that comes from the `makeCluster()` part of the parallel package. The code I'm running does not include this function, but I see it is a function in `cftdata()`.

It seems like it is a [known issue](https://github.com/rstudio/rstudio/issues/6692) with the package. The code breaks with version 4.1 of R, but works for version 4.0.5

**Comment by acrunyon** [comment]
According to the[ News for R version 4.1](https://cran.r-project.org/doc/manuals/r-release/NEWS.pdf),  parallel::detectCores() is depreciated/defunct.  It appears that there are workaround, but I don't know if these will affect the overall stability of the function.

**Comment by ttuff** [comment]
We have switched out the parallelization functions underlying cft. The new functions should be more stable. Please let us know if you're still having trouble.
