### ISSUE TITLE
Add tests for missing calls in codecov

### ISSUE THREAD

**Issue by WilliamsTravis** [earthlab/cft#19]
Add tests for anything missing in codecov.

**Comment by WilliamsTravis** [comment]
aws.s3 might have some examples  in their test suite.

**Comment by WilliamsTravis** [comment]
Test coverage remaining:

aws.R - line 17, which creates the configuration directory if it isn't present, is apparently not covered. Does travis/codecov already have a "~/.aws" directory?


cstdata.R - lines 123 - 128 & 160, which are only run if 'store_remotely is' TRUE, are not covered yet. Without providing genuine credentials, the whole run will fail, but these lines could be tested if we expected a certain error.


install_py_deps.py - line 47, which restarts rstudio is not covered. The argument 'restart_session' is set to TRUE, so 'rstudioapi::hasFun("restartSession")' must not be.


shapefile.R - line 6, which uses a user-specified shapefile path instead of the national park boundary shapefile, is not covered. Just add a test to 'get_aoi' that reads a remote zipped shapefile.


subsetting.R - line 206, which creates a locally stored destination folder if it doesn't exists, isn't covered. Is this created previously in cstdata?
                     - lines 212 - 215, which extract path information from the queries object if 'store_remotely' is TRUE, is not covered because we don't have a test for that condition.
                      - lines 317 - 326, which actually push the files to the remote storage, are also not covered for the same reason. 


zzz.R - line 12, which sets the number of cores at a max of 2 in case of a testing limit, is not run. It is instead running the next line, which sets no max...testing on travis had failed before I added this in, but now its passing without, seemingly, using the main bit of the function! No idea.

**Comment by mbjoseph** [comment]
Closing this - I started a more specific issue for AWS stuff here: #44
