### ISSUE TITLE
Transferring ownership of repo to earthlab

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/cft#26]
Heya @WilliamsTravis if it's alright with you, I'd propose we transfer ownership of this repo to the earthlab GitHub org. That way it's off your plate maintenance-wise once your current work ends. Does that sound good?

**Comment by WilliamsTravis** [comment]
Hi, yes I was thinking the same thing. Let's do that.

**Comment by mbjoseph** [comment]
Great - @WilliamsTravis could you grant me admin permissions to this repo? Then, I can transfer everything over.

**Comment by WilliamsTravis** [comment]
Sure thing...what's the best way to do that?

**Comment by mbjoseph** [comment]
See https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/adding-outside-collaborators-to-repositories-in-your-organization

**Comment by WilliamsTravis** [comment]
On step 7 "Next to the new collaborator's name, choose the appropriate permission level: Write, Read, or Admin.", there was no such option. I sent another invitation in case that jostles it and let's me change permissions. I'll have to do this after work though.

**Comment by WilliamsTravis** [comment]
I couldn't find a way to give you admin privileges (missing dropdown menu), so I just went ahead and moved it over to earthlab. I included the analytics team as collaborators, too.

**Comment by mbjoseph** [comment]
Nice - thanks!
