### ISSUE TITLE
Document how we are averaging spatially

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/cft#79]
We should document how spatial averages are being computed (centroids within polygons, or pixels touching the polygon?).

**Comment by mbjoseph** [comment]
According to @WilliamsTravis we are currently doing "all-touch" summarization - any cell within or touching the polygon is included. But, still need to check on some specific examples (Yellowstone may have some pixels that are not included).

**Comment by WilliamsTravis** [comment]
Documented as a note in the updated cst-intro. Should we create a more explicit entry for this?

**Comment by mbjoseph** [comment]
@WilliamsTravis can you reference a commit? I can't find where you added a note to document how we are averaging.

**Comment by mbjoseph** [comment]
@WilliamsTravis solved this with https://github.com/earthlab/cst/commit/5429f8229dde7853394815673e5ff4efaa6e8ad8#diff-92645435b9fc03466c2a0a2c7ef86cdd
