### ISSUE TITLE
Provide the cst data.frame as an argument to compare_periods

### ISSUE THREAD

**Issue by mbjoseph** [earthlab/cft#81]
Let's only read and process the data from .nc files in the `cst_df` function, and use the output of `cst_df` as input for `compare_periods`.

**Comment by mbjoseph** [comment]
The reason we're doing this is to allow users to generate new quantities and then visualize them in `compare_periods()`

**Comment by WilliamsTravis** [comment]
For this strategy, I think we should convert to Celsius (if we still want to do that for users) at the cst_df stage, because user defined variables would be impossible to identify.

**Comment by mbjoseph** [comment]
Sounds good!

**Comment by mbjoseph** [comment]
Leaving this open until we convert to C @WilliamsTravis

**Comment by WilliamsTravis** [comment]
This is done in the "convert_temperature" branch, but I'm not pushing to master until I know I won't mess the documentation up.
